/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EligibilityRouteImport } from './routes/Eligibility'
import { Route as GuideRouteImport } from './routes/Guide'
import { Route as InstitutionsRouteImport } from './routes/Institutions'
import { Route as ProgrammesRouteImport } from './routes/Programmes'
import { Route as EligibilityIndexRouteImport } from './routes/Eligibility.index'
import { Route as EligibilityResultsRouteImport } from './routes/Eligibility.results'
import { Route as InstitutionsInstitutionRouteImport } from './routes/Institutions_.$institution'
import { Route as ProgrammesCodeRouteImport } from './routes/programmes.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/Eligibility',
  path: '/Eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/Guide',
  path: '/Guide',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/Institutions',
  path: '/Institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/Programmes',
  path: '/Programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityIndexRoute = EligibilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EligibilityRoute,
} as any)
const EligibilityResultsRoute = EligibilityResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => EligibilityRoute,
} as any)
const InstitutionsInstitutionRoute = InstitutionsInstitutionRouteImport.update({
  id: '/Institutions_/$institution',
  path: '/Institutions/$institution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesCodeRoute = ProgrammesCodeRouteImport.update({
  id: '/programmes/$code',
  path: '/programmes/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Eligibility': typeof EligibilityRouteWithChildren
  '/Guide': typeof GuideRoute
  '/Institutions': typeof InstitutionsRoute
  '/Programmes': typeof ProgrammesRoute
  '/Eligibility/results': typeof EligibilityResultsRoute
  '/Institutions/$institution': typeof InstitutionsInstitutionRoute
  '/programmes/$code': typeof ProgrammesCodeRoute
  '/Eligibility/': typeof EligibilityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Guide': typeof GuideRoute
  '/Institutions': typeof InstitutionsRoute
  '/Programmes': typeof ProgrammesRoute
  '/Eligibility/results': typeof EligibilityResultsRoute
  '/Institutions/$institution': typeof InstitutionsInstitutionRoute
  '/programmes/$code': typeof ProgrammesCodeRoute
  '/Eligibility': typeof EligibilityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Eligibility': typeof EligibilityRouteWithChildren
  '/Guide': typeof GuideRoute
  '/Institutions': typeof InstitutionsRoute
  '/Programmes': typeof ProgrammesRoute
  '/Eligibility/results': typeof EligibilityResultsRoute
  '/Institutions_/$institution': typeof InstitutionsInstitutionRoute
  '/programmes/$code': typeof ProgrammesCodeRoute
  '/Eligibility/': typeof EligibilityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Eligibility'
    | '/Guide'
    | '/Institutions'
    | '/Programmes'
    | '/Eligibility/results'
    | '/Institutions/$institution'
    | '/programmes/$code'
    | '/Eligibility/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Guide'
    | '/Institutions'
    | '/Programmes'
    | '/Eligibility/results'
    | '/Institutions/$institution'
    | '/programmes/$code'
    | '/Eligibility'
  id:
    | '__root__'
    | '/'
    | '/Eligibility'
    | '/Guide'
    | '/Institutions'
    | '/Programmes'
    | '/Eligibility/results'
    | '/Institutions_/$institution'
    | '/programmes/$code'
    | '/Eligibility/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EligibilityRoute: typeof EligibilityRouteWithChildren
  GuideRoute: typeof GuideRoute
  InstitutionsRoute: typeof InstitutionsRoute
  ProgrammesRoute: typeof ProgrammesRoute
  InstitutionsInstitutionRoute: typeof InstitutionsInstitutionRoute
  ProgrammesCodeRoute: typeof ProgrammesCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Eligibility': {
      id: '/Eligibility'
      path: '/Eligibility'
      fullPath: '/Eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Guide': {
      id: '/Guide'
      path: '/Guide'
      fullPath: '/Guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Institutions': {
      id: '/Institutions'
      path: '/Institutions'
      fullPath: '/Institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Programmes': {
      id: '/Programmes'
      path: '/Programmes'
      fullPath: '/Programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Eligibility/': {
      id: '/Eligibility/'
      path: '/'
      fullPath: '/Eligibility/'
      preLoaderRoute: typeof EligibilityIndexRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/Eligibility/results': {
      id: '/Eligibility/results'
      path: '/results'
      fullPath: '/Eligibility/results'
      preLoaderRoute: typeof EligibilityResultsRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/Institutions_/$institution': {
      id: '/Institutions_/$institution'
      path: '/Institutions/$institution'
      fullPath: '/Institutions/$institution'
      preLoaderRoute: typeof InstitutionsInstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$code': {
      id: '/programmes/$code'
      path: '/programmes/$code'
      fullPath: '/programmes/$code'
      preLoaderRoute: typeof ProgrammesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EligibilityRouteChildren {
  EligibilityResultsRoute: typeof EligibilityResultsRoute
  EligibilityIndexRoute: typeof EligibilityIndexRoute
}

const EligibilityRouteChildren: EligibilityRouteChildren = {
  EligibilityResultsRoute: EligibilityResultsRoute,
  EligibilityIndexRoute: EligibilityIndexRoute,
}

const EligibilityRouteWithChildren = EligibilityRoute._addFileChildren(
  EligibilityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EligibilityRoute: EligibilityRouteWithChildren,
  GuideRoute: GuideRoute,
  InstitutionsRoute: InstitutionsRoute,
  ProgrammesRoute: ProgrammesRoute,
  InstitutionsInstitutionRoute: InstitutionsInstitutionRoute,
  ProgrammesCodeRoute: ProgrammesCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
