/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EligibilityRouteImport } from './routes/Eligibility'
import { Route as GuideRouteImport } from './routes/Guide'
import { Route as InstitutionsRouteImport } from './routes/Institutions'
import { Route as ProgrammesRouteImport } from './routes/Programmes'
import { Route as EligiibilityResultsRouteImport } from './routes/Eligiibility.results'
import { Route as ProgrammesCodeRouteImport } from './routes/programmes.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/Eligibility',
  path: '/Eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/Guide',
  path: '/Guide',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/Institutions',
  path: '/Institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/Programmes',
  path: '/Programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const EligiibilityResultsRoute = EligiibilityResultsRouteImport.update({
  id: '/Eligiibility/results',
  path: '/Eligiibility/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesCodeRoute = ProgrammesCodeRouteImport.update({
  id: '/programmes/$code',
  path: '/programmes/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Eligibility': typeof EligibilityRoute
  '/Guide': typeof GuideRoute
  '/Institutions': typeof InstitutionsRoute
  '/Programmes': typeof ProgrammesRoute
  '/Eligiibility/results': typeof EligiibilityResultsRoute
  '/programmes/$code': typeof ProgrammesCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Eligibility': typeof EligibilityRoute
  '/Guide': typeof GuideRoute
  '/Institutions': typeof InstitutionsRoute
  '/Programmes': typeof ProgrammesRoute
  '/Eligiibility/results': typeof EligiibilityResultsRoute
  '/programmes/$code': typeof ProgrammesCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Eligibility': typeof EligibilityRoute
  '/Guide': typeof GuideRoute
  '/Institutions': typeof InstitutionsRoute
  '/Programmes': typeof ProgrammesRoute
  '/Eligiibility/results': typeof EligiibilityResultsRoute
  '/programmes/$code': typeof ProgrammesCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Eligibility'
    | '/Guide'
    | '/Institutions'
    | '/Programmes'
    | '/Eligiibility/results'
    | '/programmes/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Eligibility'
    | '/Guide'
    | '/Institutions'
    | '/Programmes'
    | '/Eligiibility/results'
    | '/programmes/$code'
  id:
    | '__root__'
    | '/'
    | '/Eligibility'
    | '/Guide'
    | '/Institutions'
    | '/Programmes'
    | '/Eligiibility/results'
    | '/programmes/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EligibilityRoute: typeof EligibilityRoute
  GuideRoute: typeof GuideRoute
  InstitutionsRoute: typeof InstitutionsRoute
  ProgrammesRoute: typeof ProgrammesRoute
  EligiibilityResultsRoute: typeof EligiibilityResultsRoute
  ProgrammesCodeRoute: typeof ProgrammesCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Eligibility': {
      id: '/Eligibility'
      path: '/Eligibility'
      fullPath: '/Eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Guide': {
      id: '/Guide'
      path: '/Guide'
      fullPath: '/Guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Institutions': {
      id: '/Institutions'
      path: '/Institutions'
      fullPath: '/Institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Programmes': {
      id: '/Programmes'
      path: '/Programmes'
      fullPath: '/Programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Eligiibility/results': {
      id: '/Eligiibility/results'
      path: '/Eligiibility/results'
      fullPath: '/Eligiibility/results'
      preLoaderRoute: typeof EligiibilityResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$code': {
      id: '/programmes/$code'
      path: '/programmes/$code'
      fullPath: '/programmes/$code'
      preLoaderRoute: typeof ProgrammesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EligibilityRoute: EligibilityRoute,
  GuideRoute: GuideRoute,
  InstitutionsRoute: InstitutionsRoute,
  ProgrammesRoute: ProgrammesRoute,
  EligiibilityResultsRoute: EligiibilityResultsRoute,
  ProgrammesCodeRoute: ProgrammesCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
